site: Milanow
title: Milanow
greetings: Cheers love, the cavalry's here! 👋
description: >- 
  My work mainly focuses on building different system architectures to make the business ticks in a healthy way. I’ve been building softwares for many different aspects. From iOS development in Unity3D, infrastructure for autonomous driving to one of the greatest collaborating software - Feishu/Lark. Recently I am busy trying to switch most of my technical skills towards AI & XR. Learning new stuff can inspire my daily work either. I love these new technologies to keep the world moving forwards to unknown way. Working on migrating my side projects here, keep on eye for them!
lang: en-US
timezone:  Asia/Beijing
repo: https://github.com/milanow/milanow.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: milanow
  bio: a software engineer, loving sport, game and anything else
  userpicture: 
  username: milanow # general username
  github: milanow # github username
  twitter: milanowth # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  threads: milanow # threads name
  email: wthsylor@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://milanow.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


